//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.06 at 10:51:33 PM IST 
//


package de.zib.sndlib.network;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for network complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="network">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="networkStructure" type="{http://sndlib.zib.de/network}networkStructure" minOccurs="0"/>
 *         &lt;element name="demands" type="{http://sndlib.zib.de/network}demands" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "network", propOrder = {
    "networkStructure",
    "demands"
})
public class Network {

    protected NetworkStructure networkStructure;
    protected Demands demands;
    @XmlAttribute
    protected BigDecimal version;

    /**
     * Gets the value of the networkStructure property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkStructure }
     *     
     */
    public NetworkStructure getNetworkStructure() {
        return networkStructure;
    }

    /**
     * Sets the value of the networkStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkStructure }
     *     
     */
    public void setNetworkStructure(NetworkStructure value) {
        this.networkStructure = value;
    }

    /**
     * Gets the value of the demands property.
     * 
     * @return
     *     possible object is
     *     {@link Demands }
     *     
     */
    public Demands getDemands() {
        return demands;
    }

    /**
     * Sets the value of the demands property.
     * 
     * @param value
     *     allowed object is
     *     {@link Demands }
     *     
     */
    public void setDemands(Demands value) {
        this.demands = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

}
