//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.06 at 10:51:33 PM IST 
//


package de.zib.sndlib.network;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.zib.sndlib.network package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NetworkStructure_QNAME = new QName("http://sndlib.zib.de/network", "networkStructure");
    private final static QName _Links_QNAME = new QName("http://sndlib.zib.de/network", "links");
    private final static QName _AdditionalModules_QNAME = new QName("http://sndlib.zib.de/network", "additionalModules");
    private final static QName _Network_QNAME = new QName("http://sndlib.zib.de/network", "network");
    private final static QName _Coordinates_QNAME = new QName("http://sndlib.zib.de/network", "coordinates");
    private final static QName _AddModule_QNAME = new QName("http://sndlib.zib.de/network", "addModule");
    private final static QName _Demands_QNAME = new QName("http://sndlib.zib.de/network", "demands");
    private final static QName _Link_QNAME = new QName("http://sndlib.zib.de/network", "link");
    private final static QName _Nodes_QNAME = new QName("http://sndlib.zib.de/network", "nodes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.zib.sndlib.network
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdditionalModules }
     * 
     */
    public AdditionalModules createAdditionalModules() {
        return new AdditionalModules();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link NetworkStructure }
     * 
     */
    public NetworkStructure createNetworkStructure() {
        return new NetworkStructure();
    }

    /**
     * Create an instance of {@link Demand }
     * 
     */
    public Demand createDemand() {
        return new Demand();
    }

    /**
     * Create an instance of {@link Network }
     * 
     */
    public Network createNetwork() {
        return new Network();
    }

    /**
     * Create an instance of {@link Nodes }
     * 
     */
    public Nodes createNodes() {
        return new Nodes();
    }

    /**
     * Create an instance of {@link Coordinates }
     * 
     */
    public Coordinates createCoordinates() {
        return new Coordinates();
    }

    /**
     * Create an instance of {@link Links }
     * 
     */
    public Links createLinks() {
        return new Links();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Demands }
     * 
     */
    public Demands createDemands() {
        return new Demands();
    }

    /**
     * Create an instance of {@link AddModule }
     * 
     */
    public AddModule createAddModule() {
        return new AddModule();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sndlib.zib.de/network", name = "networkStructure")
    public JAXBElement<NetworkStructure> createNetworkStructure(NetworkStructure value) {
        return new JAXBElement<NetworkStructure>(_NetworkStructure_QNAME, NetworkStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Links }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sndlib.zib.de/network", name = "links")
    public JAXBElement<Links> createLinks(Links value) {
        return new JAXBElement<Links>(_Links_QNAME, Links.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdditionalModules }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sndlib.zib.de/network", name = "additionalModules")
    public JAXBElement<AdditionalModules> createAdditionalModules(AdditionalModules value) {
        return new JAXBElement<AdditionalModules>(_AdditionalModules_QNAME, AdditionalModules.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Network }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sndlib.zib.de/network", name = "network")
    public JAXBElement<Network> createNetwork(Network value) {
        return new JAXBElement<Network>(_Network_QNAME, Network.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Coordinates }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sndlib.zib.de/network", name = "coordinates")
    public JAXBElement<Coordinates> createCoordinates(Coordinates value) {
        return new JAXBElement<Coordinates>(_Coordinates_QNAME, Coordinates.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddModule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sndlib.zib.de/network", name = "addModule")
    public JAXBElement<AddModule> createAddModule(AddModule value) {
        return new JAXBElement<AddModule>(_AddModule_QNAME, AddModule.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Demands }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sndlib.zib.de/network", name = "demands")
    public JAXBElement<Demands> createDemands(Demands value) {
        return new JAXBElement<Demands>(_Demands_QNAME, Demands.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Link }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sndlib.zib.de/network", name = "link")
    public JAXBElement<Link> createLink(Link value) {
        return new JAXBElement<Link>(_Link_QNAME, Link.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Nodes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sndlib.zib.de/network", name = "nodes")
    public JAXBElement<Nodes> createNodes(Nodes value) {
        return new JAXBElement<Nodes>(_Nodes_QNAME, Nodes.class, null, value);
    }

}
